# fly.toml app configuration file generated for spookexam-purple-shape-2866 on 2024-11-03T19:06:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spookexam-purple-shape-2866'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
